### PR TITLE
add support for python 3

### PR DESCRIPTION
**Pull request by migueldvb**

### CODE REVIEW

**Comment by mkelley** [comment]
This is great!  I've been meaning to start the move to 3 for a while.  Give me a few days to get my virtualenv's working and I will review it and any other needed 2 to 3 fixes.

**Comment by migueldvb** [comment]
Thanks! I think that in some files a line with 'from __future__ import
print_function' will be needed to be compatible with python 2.6 if
that is a requirement.

**Comment by mkelley** [comment]
Can you instead make this pull request on the dev branch?  I think this will be a big enough change that I'd like some time working out any bugs before merging to master.

**Comment by migueldvb** [comment]
It looks like the only way to do this is to close this PR and open a new one based on the dev branch.

**Pull request closed without merging**
